SHELL := /bin/bash

FLUTTER      := flutter
APP_DIR      := app
PROXY_DIR    := proxy

# Snap Flutter bundles LLVM 10 without a linker; native_toolchain_c (pulled
# in by flutter_secure_storage_linux) needs ld.lld. Prepend system LLVM 20 bin
# so it finds the right toolchain before the snap's incomplete LLVM 10.
LLVM_BIN     := /usr/lib/llvm-20/bin

# Sentinel: regenerated by `flutter pub get`. Depends on pubspec files.
# Make skips pub get unless pubspec.yaml or pubspec.lock changed.
PUB_STAMP    := $(APP_DIR)/.dart_tool/package_config.json

# ── Bootstrap ────────────────────────────────────────────────────────────────

# Check system deps, then fetch pub deps.
.PHONY: setup
setup:
	./scripts/setup.sh
	cd $(APP_DIR) && $(FLUTTER) pub get

# Fetch pub deps only when pubspec files are newer than the stamp.
$(PUB_STAMP): $(APP_DIR)/pubspec.yaml $(APP_DIR)/pubspec.lock
	cd $(APP_DIR) && $(FLUTTER) pub get

# ── Dev ──────────────────────────────────────────────────────────────────────
.PHONY: run run-linux run-windows run-windows-test run-windows-simple
run:
	@echo "Please specify a platform: make run-linux or make run-windows"
run-linux: $(PUB_STAMP)
	cd $(APP_DIR) && PATH="$(LLVM_BIN):$$PATH" GDK_BACKEND=x11 XAUTHORITY=$$(ls /run/user/$$(id -u)/.mutter-Xwaylandauth.* 2>/dev/null | head -1) $(FLUTTER) run -d linux
run-windows: $(PUB_STAMP)
	cd $(APP_DIR) && $(FLUTTER) run -d windows
run-windows-test: $(PUB_STAMP)
	cd $(APP_DIR) && $(FLUTTER) run -d windows --target lib/windows_test.dart
run-windows-simple: $(PUB_STAMP)
	cd $(APP_DIR) && $(FLUTTER) run -d windows --target lib/simple_main.dart

# ── Test ─────────────────────────────────────────────────────────────────────
.PHONY: test
test: $(PUB_STAMP)
	cd $(APP_DIR) && $(FLUTTER) test --coverage

.PHONY: test-watch
test-watch: $(PUB_STAMP)
	cd $(APP_DIR) && $(FLUTTER) test --coverage --watch

.PHONY: integration-test integration-test-linux integration-test-windows
integration-test:
	@echo "Please specify a platform: make integration-test-linux or make integration-test-windows"
integration-test-linux: $(PUB_STAMP)
	cd $(APP_DIR) && PATH="$(LLVM_BIN):$$PATH" GDK_BACKEND=x11 XAUTHORITY=$$(ls /run/user/$$(id -u)/.mutter-Xwaylandauth.* 2>/dev/null | head -1) $(FLUTTER) test integration_test/ -d linux
integration-test-windows: $(PUB_STAMP)
	cd $(APP_DIR) && $(FLUTTER) test integration_test/ -d windows

# ── Build ────────────────────────────────────────────────────────────────────
.PHONY: build-linux build-macos build-windows
build-linux: $(PUB_STAMP)
	cd $(APP_DIR) && PATH="$(LLVM_BIN):$$PATH" $(FLUTTER) build linux --release

build-macos: $(PUB_STAMP)
	cd $(APP_DIR) && $(FLUTTER) build macos --release

build-windows: $(PUB_STAMP)
	cd $(APP_DIR) && $(FLUTTER) build windows --release

# ── Quality ──────────────────────────────────────────────────────────────────
.PHONY: format analyze lint lint-style lint-metrics lint-format
format: $(PUB_STAMP)
	cd $(APP_DIR) && dart format lib/ test/

analyze: $(PUB_STAMP)
	cd $(APP_DIR) && $(FLUTTER) analyze

# Comprehensive linting (Style + Complexity + Duplication + Formatting)
lint: lint-style lint-metrics lint-format

# Basic Flutter analyzer (Style) - Fatal on errors and warnings
lint-style: $(PUB_STAMP)
	cd $(APP_DIR) && $(FLUTTER) analyze --fatal-warnings

# Complexity and Duplication metrics
lint-metrics: $(PUB_STAMP)
	cd $(APP_DIR) && $(FLUTTER) pub run dart_code_linter:metrics check-unused-files lib
	cd $(APP_DIR) && $(FLUTTER) pub run dart_code_linter:metrics analyze lib --fatal-style --fatal-performance --fatal-warnings

# Formatting check (non-modifying)
lint-format: $(PUB_STAMP)
	cd $(APP_DIR) && dart format --output=none --set-exit-if-changed lib/ test/

# ── Proxy ────────────────────────────────────────────────────────────────────
# Runs the local OAuth token exchange proxy. The proxy adds client_secret
# server-side so the app binary never contains the secret.
#
# Usage:
#   export GOOGLE_CLIENT_SECRET=<your_secret>
#   make proxy
#
.PHONY: proxy proxy-setup
proxy-setup:
	cd $(PROXY_DIR) && dart pub get

proxy: proxy-setup
	@test -n "$$GOOGLE_CLIENT_SECRET" || \
		(echo "Error: GOOGLE_CLIENT_SECRET is not set. Run: export GOOGLE_CLIENT_SECRET=<secret>"; exit 1)
	cd $(PROXY_DIR) && dart run bin/server.dart

# ── TLDR ─────────────────────────────────────────────────────────────────────
.PHONY: tldr
tldr:
	@rg "TL*DR" . -B2 -A6 --glob="*.{dart,md}"


# ── Clean ────────────────────────────────────────────────────────────────────
.PHONY: clean
clean:
	cd $(APP_DIR) && $(FLUTTER) clean

# ── Help ─────────────────────────────────────────────────────────────────────
.PHONY: help
help:
	@echo "Happening — Makefile targets"
	@echo ""
	@echo "  make setup        Check system deps + fetch pub deps"
	@echo "  make run          Run app (use 'run-linux' or 'run-windows')"
	@echo "  make run-linux    Run app on Linux desktop"
	@echo "  make run-windows  Run app on Windows desktop"
	@echo "  make test         Run all tests with coverage"
	@echo "  make integration-test  Run integration tests (use 'integration-test-linux' or 'integration-test-windows')"
	@echo "  make integration-test-linux  Run integration tests on Linux"
	@echo "  make integration-test-windows  Run integration tests on Windows"
	@echo "  make build-linux  Release build for Linux"
	@echo "  make build-macos  Release build for macOS"
	@echo "  make build-windows Release build for Windows"
	@echo "  make format       Format all Dart source"
	@echo "  make analyze      Run Dart analyzer"
	@echo "  make lint         Run all lint checks (style, metrics, format)"
	@echo "  make lint-style   Run Flutter analyzer with fatal flags"
	@echo "  make lint-metrics Run complexity and performance metrics"
	@echo "  make lint-format  Check if code is correctly formatted"
	@echo "  make tldr         Print TLDR header map of all lib source files"
	@echo "  make proxy        Run OAuth token exchange proxy (requires GOOGLE_CLIENT_SECRET)"
	@echo "  make proxy-setup  Install proxy dependencies"
	@echo "  make clean        Remove build artifacts"
