SHELL := /bin/bash

FLUTTER      := flutter
APP_DIR      := app

# Sentinel: regenerated by `flutter pub get`. Depends on pubspec files.
# Make skips pub get unless pubspec.yaml or pubspec.lock changed.
PUB_STAMP    := $(APP_DIR)/.dart_tool/package_config.json

# ── Bootstrap ────────────────────────────────────────────────────────────────

# Check system deps, then fetch pub deps.
.PHONY: setup
setup:
	./scripts/setup.sh
	cd $(APP_DIR) && $(FLUTTER) pub get

# Fetch pub deps only when pubspec files are newer than the stamp.
$(PUB_STAMP): $(APP_DIR)/pubspec.yaml $(APP_DIR)/pubspec.lock
	cd $(APP_DIR) && $(FLUTTER) pub get

# ── Dev ──────────────────────────────────────────────────────────────────────
.PHONY: run
run: $(PUB_STAMP)
	cd $(APP_DIR) && GDK_BACKEND=x11 $(FLUTTER) run -d linux

# ── Test ─────────────────────────────────────────────────────────────────────
.PHONY: test
test: $(PUB_STAMP)
	cd $(APP_DIR) && $(FLUTTER) test --coverage

.PHONY: test-watch
test-watch: $(PUB_STAMP)
	cd $(APP_DIR) && $(FLUTTER) test --coverage --watch

# ── Build ────────────────────────────────────────────────────────────────────
.PHONY: build-linux build-macos build-windows
build-linux: $(PUB_STAMP)
	cd $(APP_DIR) && $(FLUTTER) build linux --release

build-macos: $(PUB_STAMP)
	cd $(APP_DIR) && $(FLUTTER) build macos --release

build-windows: $(PUB_STAMP)
	cd $(APP_DIR) && $(FLUTTER) build windows --release

# ── Quality ──────────────────────────────────────────────────────────────────
.PHONY: format analyze
format: $(PUB_STAMP)
	cd $(APP_DIR) && $(FLUTTER) format lib/ test/

analyze: $(PUB_STAMP)
	cd $(APP_DIR) && $(FLUTTER) analyze

# ── Clean ────────────────────────────────────────────────────────────────────
.PHONY: clean
clean:
	cd $(APP_DIR) && $(FLUTTER) clean

# ── Help ─────────────────────────────────────────────────────────────────────
.PHONY: help
help:
	@echo "Happening — Makefile targets"
	@echo ""
	@echo "  make setup        Check system deps + fetch pub deps"
	@echo "  make run          Run app on Linux desktop"
	@echo "  make test         Run all tests with coverage"
	@echo "  make build-linux  Release build for Linux"
	@echo "  make build-macos  Release build for macOS"
	@echo "  make format       Format all Dart source"
	@echo "  make analyze      Run Dart analyzer"
	@echo "  make clean        Remove build artifacts"
